// Backend API configuration
const API_BASE_URL = 'https://skillful-nature-production.up.railway.app';

// Token management
function saveToken(token) {
    localStorage.setItem('authToken', token);
}

function getToken() {
    return localStorage.getItem('authToken');
}

// API call helper
async function apiCall(endpoint, method = 'GET', data = null, requiresAuth = false) {
    const headers = {
        'Content-Type': 'application/json'
    };
    
    if (requiresAuth) {
        const token = getToken();
        if (token) {
            headers['Authorization'] = `Bearer ${token}`;
        }
    }
    
    const config = {
        method,
        headers
    };
    
    if (data) {
        config.body = JSON.stringify(data);
    }
    
    try {
        const response = await fetch(`${API_BASE_URL}${endpoint}`, config);
        const result = await response.json();
        
        if (!response.ok) {
            throw new Error(result.message || 'API request failed');
        }
        
        return result;
    } catch (error) {
        console.error('API Error:', error);
        throw error;
    }
}

// Send OTP for signup
async function sendSignupOTP(email) {
    try {
        const response = await apiCall('/auth/sent/login-signup-otp', 'POST', {
            email: email,
            otp: '', // Will be generated by backend
            user: null
        });
        
        if (response.status) {
            return true;
        } else {
            throw new Error(response.message || 'Failed to send OTP');
        }
    } catch (error) {
        console.error('Send OTP error:', error);
        throw error;
    }
}

// Complete signup with OTP
async function completeSignup(fullName, email, otp) {
    try {
        const response = await apiCall('/auth/signup', 'POST', {
            fullName: fullName,
            email: email,
            otp: otp
        });
        
        if (response.status && response.jwt) {
            // Save JWT token
            saveToken(response.jwt);
            return response;
        } else {
            throw new Error(response.message || 'Signup failed');
        }
    } catch (error) {
        console.error('Signup error:', error);
        throw error;
    }
}

function togglePassword(fieldId) {
    const field = document.getElementById(fieldId);
    const toggle = field.nextElementSibling;
    
    if (field.type === 'password') {
        field.type = 'text';
        toggle.textContent = '🙈';
    } else {
        field.type = 'password';
        toggle.textContent = '👁️';
    }
}

function showTerms() {
    alert('Terms and Conditions would be displayed here.');
}

function showPrivacy() {
    alert('Privacy Policy would be displayed here.');
}

function showLogin() {
    alert('Redirecting to login page...');
}

// Global signup state
let signupState = {
    step: 1, // 1: form validation, 2: OTP verification
    userData: null
};

// Show OTP input field
function showOTPInput() {
    // Create OTP input if it doesn't exist
    let otpContainer = document.getElementById('otpContainer');
    if (!otpContainer) {
        otpContainer = document.createElement('div');
        otpContainer.id = 'otpContainer';
        otpContainer.innerHTML = `
            <div class="input-group">
                <input type="text" id="otpCode" class="form-input" placeholder="Enter OTP" maxlength="6" required>
                <label for="otpCode">OTP Code</label>
            </div>
            <button type="button" id="resendOTP" class="resend-btn">Resend OTP</button>
        `;
        
        // Insert before submit button
        const submitBtn = document.querySelector('button[type="submit"]');
        submitBtn.parentNode.insertBefore(otpContainer, submitBtn);
        
        // Add resend OTP functionality
        document.getElementById('resendOTP').addEventListener('click', async function() {
            if (signupState.userData) {
                try {
                    this.textContent = 'Sending...';
                    this.disabled = true;
                    
                    await sendSignupOTP(signupState.userData.email);
                    alert('OTP resent to your email!');
                    
                } catch (error) {
                    alert('Failed to resend OTP: ' + error.message);
                } finally {
                    this.textContent = 'Resend OTP';
                    this.disabled = false;
                }
            }
        });
    }
    
    otpContainer.style.display = 'block';
    document.getElementById('otpCode').focus();
}

// Hide OTP input field
function hideOTPInput() {
    const otpContainer = document.getElementById('otpContainer');
    if (otpContainer) {
        otpContainer.style.display = 'none';
    }
}

document.getElementById('signupForm').addEventListener('submit', async function(e) {
    e.preventDefault();
    
    const submitBtn = this.querySelector('button[type="submit"]');
    const originalText = submitBtn.textContent;
    
    if (signupState.step === 1) {
        // Step 1: Validate form and send OTP
        const fullName = document.getElementById('fullName').value;
        const email = document.getElementById('email').value;
        const password = document.getElementById('password').value;
        const confirmPassword = document.getElementById('confirmPassword').value;
        const termsAccepted = document.getElementById('terms').checked;
    
        if (!fullName || !email || !password || !confirmPassword) {
            alert('Please fill in all fields');
            return;
        }
    
        if (password !== confirmPassword) {
            alert('Passwords do not match!');
            return;
        }
        
        if (password.length < 6) {
            alert('Password must be at least 6 characters long');
            return;
        }
    
        if (!termsAccepted) {
            alert('Please accept the Terms and Conditions');
            return;
        }
        
        // Store user data for step 2
        signupState.userData = { fullName, email, password };
        
        try {
            submitBtn.textContent = 'Sending OTP...';
            submitBtn.disabled = true;
            
            await sendSignupOTP(email);
            
            alert(`OTP sent to ${email}. Please check your email and enter the code below.`);
            
            // Move to step 2
            signupState.step = 2;
            showOTPInput();
            submitBtn.textContent = 'Complete Signup';
            submitBtn.disabled = false;
            
        } catch (error) {
            alert('Failed to send OTP: ' + error.message);
            submitBtn.textContent = originalText;
            submitBtn.disabled = false;
        }
        
    } else if (signupState.step === 2) {
        // Step 2: Verify OTP and complete signup
        const otpCode = document.getElementById('otpCode').value;
        
        if (!otpCode || otpCode.length < 4) {
            alert('Please enter a valid OTP code');
            return;
        }
        
        try {
            submitBtn.textContent = 'Creating Account...';
            submitBtn.disabled = true;
            
            const response = await completeSignup(
                signupState.userData.fullName,
                signupState.userData.email,
                otpCode
            );
            
            alert(`Account created successfully for ${signupState.userData.fullName}! You are now logged in.`);
            
            // Reset form state
            signupState = { step: 1, userData: null };
            hideOTPInput();
            
            // Redirect to dashboard or home page
            // You can uncomment and modify this line based on your app structure
            // window.location.href = '/dashboard';
            
        } catch (error) {
            alert('Signup failed: ' + error.message);
        } finally {
            submitBtn.textContent = originalText;
            submitBtn.disabled = false;
        }
    }
});

// Interactive input focus effects
document.querySelectorAll('.form-input').forEach(input => {
    input.addEventListener('focus', function() {
        this.parentElement.style.transform = 'scale(1.02)';
    });
    
    input.addEventListener('blur', function() {
        this.parentElement.style.transform = 'scale(1)';
    });
});
